### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [ghosthookcc/VoxelEngine#1]
Hi. Which license applies to this project?

**Comment by ghosthookcc** [comment]
The project does not use a license, you and anybody else is free to use this project. It was my first ever c project so its a mess memory-wise but if you can get some use out of it have fun!

**Comment by LifeCANvs** [comment]
> The project does not use a license, you and anybody else is free to use this project. It was my first ever c project so its a mess memory-wise but if you can get some use out of it have fun!

Thanks, so do you mean it is like the "Unlicense license" where it can be used for any purpose by anyone? I want to let some teenagers look at it and maybe some of them will find some useful parts of code that they would want to use in their own projects...

**Comment by ghosthookcc** [comment]
I am very sorry, did not realise that i had forgotten to add a license. I will add a MIT-license when i get home today!

**Comment by ghosthookcc** [comment]
There, should be all good now. MIT-license added.

**Comment by LifeCANvs** [comment]
> There, should be all good now. MIT-license added.

Thank you so much!
